--Exploratory Data Analysis
--STEP 1: Exploring database
SELECT * FROM INFORMATION_SCHEMA.TABLES;
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'




--STEP 2: Exploring dimensions
SELECT DISTINCT country FROM gold.dim_customers;

SELECT DISTINCT CATEGORY, subcategory, product_name FROM gold.dim_products;






--STEP 3: Exploring Date
SELECT 
    MIN(order_date) firstorderdate,
    MAX(order_date) lastorderdate,
    DATEDIFF(MONTH,  MIN(order_date), MAX(order_date)) OrderRange
FROM fact_sales;

SELECT
    MIN(birthdate) Oldest_CUST,
    DATEDIFF(YEAR, MIN(birthdate), GETDATE()) OldestAge,
    MAX(birthdate) Youngest_CUST,
    DATEDIFF(YEAR, MAX(birthdate), GETDATE()) YoungestAGE
FROM gold.dim_customers;





--STEP 4: Meassure Exploration
SELECT
    SUM(sales_amount) AS Total_Sales,
    SUM(quantity) AS Total_Quantity,
    AVG(price) AS AVG_Price,
FROM dbo.fact_sales;
--checking on orders (Some dimension may be showing multiple times, 
--checking with distinct is important to compare the meaning)
SELECT COUNT(order_number) AS Total_Order FROM dbo.fact_sales;
SELECT COUNT(DISTINCT order_number) AS Total_Order FROM dbo.fact_sales;
--checking number of product
SELECT COUNT(product_key) AS Total_Product FROM gold.dim_products;
SELECT COUNT(Distinct product_key) AS Total_Product FROM gold.dim_products;
--checking number of customer
SELECT COUNT(customer_key) AS Total_Customer FROM gold.dim_customers;
--checking number of customer that has placed an order
SELECT COUNT(DISTINCT customer_key) AS Total_Customer_Sales FROM dbo.fact_sales;

-- Combine all measure to one table to make a super report of big picture
SELECT 'TOTAL SALES' as Measurement_Name, SUM(sales_amount) AS Measure_Value FROM dbo.fact_sales
UNION ALL
SELECT 'Total Quantity SOLD', SUM(quantity) AS Total_Quantity FROM dbo.fact_sales
UNION ALL
SELECT 'Avg Price', AVG(price) AS Total_Quantity FROM dbo.fact_sales
UNION ALL
SELECT 'Total Order Made', COUNT(DISTINCT order_number) AS Total_Quantity FROM dbo.fact_sales
UNION ALL
SELECT 'Total Product available to Sell', COUNT(DISTINCT product_key) AS Total_Quantity FROM gold.dim_products
UNION ALL
SELECT 'Total customer', COUNT(customer_key) AS Total_Quantity FROM gold.dim_customers
UNION ALL
SELECT 'Customer Made Purchase', COUNT(DISTINCT customer_key) AS Total_Quantity FROM dbo.fact_sales;






--STEP 5: Magnitude Analytics
--
-- the trick is to do measure by dimension
--total customer by country
SELECT 
    Country,
    COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC;

--Total customer by gender
SELECT
    Gender,
    COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customer DESC;

--Total product by category
SELECT 
    category,
    COUNT(product_key) AS total_product
FROM gold.dim_products
GROUP BY category
ORDER BY total_product DESC;

--Avg cost in each category
SELECT 
    category,
    AVG(cost) AS AVG_cost
FROM gold.dim_products
GROUP BY category
ORDER BY AVG_cost DESC;

--Total revenue generated by each category
SELECT 
    p.category,
    SUM(s.sales_amount) - SUM(p.cost) AS total_revenue
FROM dbo.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    SUM(s.sales_amount) AS total_sales
FROM gold.dim_customers c
LEFT JOIN dbo.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.customer_key, c.first_name
ORDER BY total_sales DESC;

--What is the distribution of items sold across countries
SELECT 
    c.Country,
    SUM(s.quantity) AS Total_QTY
FROM dbo.fact_sales s
LEFT JOIN  gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY Total_QTY DESC;

--Im checking IS NULL
SELECT customer_key, CASE WHEN customer_key IS NULL THEN 1 ELSE 0 END AS flag from dbo.fact_sales ORDER BY flag DESC;



--STEP 6: Ranking Exploration
--Ranking countries based on total 
--Ranking users age based on avg sales
--ranking which subcategory ofproducts based on avg revenue
--ranking top 5 product based on revenue
SELECT TOP 5
    p.product_name,
    SUM(s.sales_amount) AS total_revenue
FROM dbo.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

--least 5 top product based on revenue
SELECT TOP 5
    p.subcategory,
    SUM(s.sales_amount) AS total_revenue
FROM dbo.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.subcategory
ORDER BY total_revenue;

--top 5 poducts nased on sales revenue
SELECT TOP 5
    p.product_name,
    SUM(s.sales_amount) AS total_revenue
FROM dbo.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

SELECT
    c.customer_key,
    c.first_name,
    SUM(s.sales_amount) AS total_sales
FROM gold.dim_customers c
LEFT JOIN dbo.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.customer_key, c.first_name
ORDER BY total_sales DESC;